name: seg_bisenetv1_megastuff
trainer: segmentation_trainer.BiSeNetV1SegmentationMegastuffTrainer

model:
    backbone: bisenet_models.bisenetv1.BiSeNetV1
    n_classes: 182
    # pretrained_ckpt: /home/yuyang/data/aachen/Aachen-Day-Night/weights/mlifeat128megacoco/segmentation.pt

test:
    dataset: cocostuff_dataset.CocoStuff10k
    root: /home/yuyang/data/coco-stuff-10k

    split: test
    augment: false
    flip: false

train:
    adjust_lr: true
    lr: 0.001
    ignore_label: 255
    weight_decay: 0.0001
    lr_decay: 10
    poly_power: 0.9
    batch_size: 64
    epoch_num: 300
    log_freq: 50
    num_workers: 16
    validate_after: 0.0

    split: train
    augment: true
    flip: true
    scales: [0.5, 0.75, 1.0, 1.25, 1.5]

    dataset: megadepth_cocostuff_dataset.MegadepthCocostuffDataset
    coco_dataset_dir: /home/yuyang/data/coco-stuff-10k
    megadepth_dataset_dir: /data/yuyang/MegaDepthOrder/224/dataset
    megadepth_label_dir: /data/yuyang/MegaDepthOrder/224/points

    height: 224
    width: 224











