name: seg_bisenetv1_cocostuff164k
trainer: segmentation_trainer.BiSeNetV1SegmentationTrainer

model:
    backbone: bisenet_models.bisenetv1.BiSeNetV1
    n_classes: 182
    # pretrained_ckpt: /home/yuyang/data/aachen/Aachen-Day-Night/weights/mlifeat128megacoco/segmentation.pt

test:
    dataset: cocostuff_dataset.CocoStuff164k
    root: /home/yuyang/data/coco-stuff-164k

    split: val2017
    augment: false
    flip: false

train:
    adjust_lr: true
    lr: 0.001
    ignore_label: 255
    weight_decay: 0.0001
    lr_decay: 10
    poly_power: 0.9
    batch_size: 64
    epoch_num: 150
    log_freq: 100
    num_workers: 16
    validate_after: 0.0

    split: train2017
    augment: true
    flip: true
    scales: [0.5, 0.75, 1.0, 1.25, 1.5]

    dataset: cocostuff_dataset.CocoStuff164k
    root: /home/yuyang/data/coco-stuff-164k











