hpatches:
    dataset_dir: /data/yuyang/hpatches-sequences-release
    resize: false
    grayscale: false

model:
    name: bisenetv1_plus_point
    detection_threshold: 0.95
    dim: 128
    nms_dist: 4
    nms_radius: 4
    border_remove: 4
    weights: /home/yuyang/data/aachen/Aachen-Day-Night/weights/seg_related/bisenetv1_no_seg_cocostuff10k
    train_seg: true

    use_pretrain: true
    segmentor_ckpt: /home/yuyang/data/aachen/Aachen-Day-Night/weights/seg_related/seg_bisenetv1/model_150.pt

keys: keypoints,descriptors,shape



