ckpt_path: /home/yuyang/project/development/MegPoint/pretrained_models/magicpoint_coco.pt

dataset: megadepth_dataset.MegaDepthAdaptionDataset
labeler: keypoint_labeler.MegadepthLabeler

dataset_root: /data/yuyang/MegaDepthOrder/224/dataset
output_root: /data/yuyang/MegaDepthOrder/224/points

adaption_num: 100
top_k: 1000
nms_threshold: 4
detection_threshold: 0.04







