labeler: des_labeler.TrainDatasetCreator
base_path: /data/yuyang/MegaDepthOrder
scene_info_path: /data/yuyang/MegaDepthOrder/scene_info
ckpt_path: /home/changwei/scalepoint/ckpt/scalepoint_megacoco_step3_keypoint5/model_29.pt
output_despoint: /data/changwei/Mega_train/iteration3/despoint5
input_image: /data/changwei/Mega_train/iteration0/image
input_info: /data/changwei/Mega_train/iteration2/keypoint5
scenes_path: /data/changwei/MegaDepthOrder
adaption_num: 100
top_k: 400
nms_threshold: 4
nms_kernel_size: 5
nms_radius: 5
detection_threshold: 0.04
train: True
image_height: 240
image_width: 320
border_remove: 4





