ckpt_path: /home/yuyang/project/development/MegPoint/pretrained_models/magicpoint_coco.pt

dataset: cocostuff_dataset.CocoStuff10kRaw
labeler: keypoint_labeler.Cocostuff10kLabeler

root: /home/yuyang/data/coco-stuff-10k
output_root: /home/yuyang/data/coco-stuff-10k/processed_dataset

split: train

adaption_num: 100
top_k: 1000
nms_threshold: 4
detection_threshold: 0.04







