labeler: keypoint_labeler.TrainDatasetCreator
base_path: /data/yuyang/MegaDepthOrder
scene_info_path: /data/yuyang/MegaDepthOrder/scene_info
ckpt_path: /home/changwei/scalepoint/ckpt/scalepoint_megacoco_step2/model_29.pt
output_despoint: /data/changwei/Mega_train/iteration2/despoint
output_keypoint: /data/changwei/Mega_train/iteration2/keypoint8
input_image: /data/changwei/Mega_train/iteration0/image
input_info: /data/changwei/Mega_train/iteration0/keypoint
scenes_path: /data/changwei/MegaDepthOrder
adaption_num: 100
top_k: 400
nms_point_radius: 5
nms_radius: 16
detection_threshold: 0.04
keypoint_threshold: 0.2
train: True
image_height: 240
image_width: 320
border_remove: 4
homo_times: 5
dist_threshold_gt: 1
dist_threshold_homo: 1
continue_image: 0
homo_weight: 0.2
old_weight: 0



