ckpt_path: /home/yuyang/project/development/MegPoint/pretrained_models/magicpoint_coco.pt

dataset: megadepth_dataset.MegaDepthAdaptionDataset
labeler: keypoint_labeler.MegadepthLabeler

dataset_root: /data/changwei/MegaDepthOrder/preprocessed_train_dataset
output_root: /data/changwei/MegaDepthOrder/points

adaption_num: 100
top_k: 1000
nms_threshold: 4
detection_threshold: 0.04
model:
    name: Scalepoint
    backbone: scalenet.ScaleBackbone
    detection_threshold: 0.9
    nms_dist: 4
    nms_radius: 4
    border_remove: 4
    weight_path: "/home/changwei/scalepoint/ckpt"
    ckpt_name: scalepoint_megacoco_scalepointv1
    weights_id: '29'






