model:
    name: 'aslfeat_model'
    model_path: 'weights/aslfeat/model.ckpt-380000'
    max_dim: 2000
    config:
        kpt_n: 5000
        kpt_refinement: true
        deform_desc: 1
        score_thld: 0.5
        edge_thld: 10
        multi_scale: false
        multi_level: true
        nms_size: 3
        eof_mask: 5
        need_norm: true
        use_peakiness: true

