
list_root: /data/localization/MegaDepthOrder/list/test_list

dataset_root: /data/localization/MegaDepthOrder/phoenix/S6/zl548/MegaDepth_v1

anotations: ['landscape', 'portrait']

output_root: /data/localization/MegaDepthOrder/list/test_list

processed_output_root: /data/localization/MegaDepthOrder/processed/test

min_size: 320
