
list_root: /data/localization/MegaDepthOrder/list/train_list

dataset_root: /data/localization/MegaDepthOrder/phoenix/S6/zl548/MegaDepth_v1

anotations: ['landscape', 'portrait']

output_root: /data/localization/MegaDepthOrder/list/train_list

processed_output_root: /data/localization/MegaDepthOrder/processed/train

min_size: 320

