name: bisenetv1
trainer: bisenetv1_trainer.BiSeNetV1Trainer

model:
    # backbone: bisenet_models.bisenetv1.BiSeNetV1Point
    backbone: superpoint_net.SuperPointFSMSegmentation
    n_classes: 182
    # pretrained_ckpt: /home/yuyang/data/aachen/Aachen-Day-Night/weights/mlifeat128megacoco/segmentation.pt

test:
    detection_threshold: 0.9
    correct_epsilon: 3
    top_k: 1000
    nms_threshold: 4

    dataset: hpatch_dataset.HPatchDataset
    hpatch_dataset_dir: /data/yuyang/data1/MegPoint/dataset/hpatch
    height: 480
    width: 640

train:
    adjust_lr: false
    lr: 0.001
    weight_decay: 0.0001
    batch_size: 32
    epoch_num: 50
    log_freq: 10
    num_workers: 8
    validate_after: 0.7 # 0.7
    seg_weight: 0.1

    dataset: cocostuff_dataset.CocoStuff10kTrainPoint
    root: /home/yuyang/data/coco-stuff-10k
    flip: true
    scales: [0.5, 0.75, 1.0, 1.25, 1.5]

    height: 224
    width: 224


