name: bisenetv1_mix
trainer: segmentation_trainer.SegmentationMixTrainer

model:
    backbone: bisenet_models.bisenetv1.BiSeNetV1Point
    extractor: superpoint_net.Extractor384
    n_classes: 182

    pretrained_seg_ckpt: /home/yuyang/data/aachen/Aachen-Day-Night/weights/seg_related/seg_bisenetv1/model_150.pt

    # debug use
    # backbone_ckpt: /home/yuyang/project/development/MegPoint/ckpt/bisenetv1_mix_e1/model_final.pt
    # extractor_ckpt: /home/yuyang/project/development/MegPoint/ckpt/bisenetv1_mix_e1/extractor_final.pt
    # backbone_ckpt: /home/yuyang/project/development/MegPoint/ckpt/bisenetv1_megastuff_mix_e1/model_final.pt
    # extractor_ckpt: /home/yuyang/project/development/MegPoint/ckpt/bisenetv1_megastuff_mix_e1/extractor_final.pt

test:
    detection_threshold: 0.95
    correct_epsilon: 3
    top_k: 1000
    nms_threshold: 4

    point_dataset:
        name: hpatch_dataset.HPatchDataset
        hpatch_dataset_dir: /data/yuyang/data1/MegPoint/dataset/hpatch
        height: 480
        width: 640

    seg_dataset:
        name: cocostuff_dataset.CocoStuff10kTest
        dataset_root: /home/yuyang/data/coco-stuff-10k

train:
    adjust_lr: false
    lr: 0.001
    weight_decay: 0.0001
    batch_size: 24
    epoch_num: 50
    log_freq: 50
    num_workers: 24
    validate_after: 0.8

    train_seg: false

    dataset:
        name: cocostuff_dataset.CocoStuff10kTrain
        dataset_root: /home/yuyang/data/coco-stuff-10k
        flip: true
        scales: [0.5, 0.75, 1.0, 1.25, 1.5]

        height: 224
        width: 224


