name: megpoint_bisenetv1_distill2
trainer: mlifeat_trainers.MegpointDistill2

model:
    backbone: superpoint_net.SuperPointNetBackbone3
    extractor: superpoint_net.SegExtractor384
    segmentor: bisenet_models.bisenetv1.BiSeNetV1
    segmentor_ckpt : /home/yuyang/data/aachen/Aachen-Day-Night/weights/mlifeat128megacoco/bisenetv1.pt
    n_blocks: [3,4,23,3]

test:
    detection_threshold: 0.9
    correct_epsilon: 3
    top_k: 1000
    nms_threshold: 4

    dataset: hpatch_dataset.HPatchDataset
    hpatch_dataset_dir: /data/yuyang/data1/MegPoint/dataset/hpatch
    height: 480
    width: 640

train:
    adjust_lr: true
    lr: 0.001
    weight_decay: 0.0001
    batch_size: 24
    epoch_num: 30
    log_freq: 100
    num_workers: 8
    validate_after: 0.7

    dataset: megadepth_coco_dataset.MegaDepthCOCOSegmentationDataset
    coco_dataset_dir: /data/yuyang/data1/MegPoint/dataset/coco/train2014
    megadepth_dataset_dir: /data/yuyang/MegaDepthOrder/preprocessed_train_dataset
    megadepth_label_dir: /data/yuyang/MegaDepthOrder/preprocessed_train_label

    height: 240
    width: 320

    fix_grid_option: 400
    fix_sample: false
    rotation_option: none
    do_augmentation: true



