name: scalepoint_megacoco
trainer: scale_trainers.ScalePointTrainer

model:
    backbone: scalenet.ScaleBackbone

test:
    detection_threshold: 0.9
    correct_epsilon: 3
    top_k: 1000
    nms_threshold: 4

    dataset: hpatch_dataset.HPatchDataset
    hpatch_dataset_dir: /data/yuyang/data1/MegPoint/dataset/hpatch
    height: 480
    width: 640

train:
    adjust_lr: true
    lr: 0.001
    weight_decay: 0.0001
    batch_size: 20
    epoch_num: 30
    log_freq: 100
    num_workers: 8
    validate_after: 30

    dataset: megadepth_train_dataset.MegaDepthTrainDataset
    mega_image_dir: /data/changwei/Mega_train/image_test
    mega_keypoint_dir: /data/changwei/Mega_train/keypoint_test
    mega_despoint_dir: /data/changwei/Mega_train/despoint_test
    height: 240
    width: 320

    fix_grid_option: 400
    fix_sample: false
    rotation_option: none
    do_augmentation: true



