name: superpoint_fbm
trainer: mlifeat_trainers.SuperPointFBMTrainer

model:
    backbone: superpoint_net.SuperPointDetector
    extractor: superpoint_net.SuperPointExtractor128

test:
    detection_threshold: 0.15
    correct_epsilon: 3
    top_k: 1000
    nms_threshold: 4

    dataset: hpatch_dataset.HPatchDataset
    hpatch_dataset_dir: /data/yuyang/data1/MegPoint/dataset/hpatch
    height: 480
    width: 640

train:
    adjust_lr: true
    lr: 0.001
    weight_decay: 0.0001
    batch_size: 24
    epoch_num: 30
    log_freq: 100
    num_workers: 8

    dataset: megadepth_coco_dataset.MegaDepthCOCOSuperPointDataset
    coco_dataset_dir: /data/yuyang/data1/MegPoint/dataset/coco/train2014
    megadepth_dataset_dir: /data/yuyang/MegaDepthOrder/preprocessed_train_dataset
    megadepth_label_dir: /data/yuyang/MegaDepthOrder/preprocessed_train_label

    height: 240
    width: 320

    fix_grid_option: 400
    fix_sample: false
    rotation_option: none
    do_augmentation: true




