methods: mlifeat128megacoco,d2netss,d2netms,r2d2,aslfeat,superpoint,superpoint_selftrained_megacoco,affnet,dsp-sift

names: MLIFeat,D2Net-SS,D2Net-MS,R2D2,ASLFeat,SuperPoint-Orig,SuperPoint-Impl,HesAffNet+HardNet++,DSP-SIFT

colors: red,blue,mediumblue,dodgerblue,gold,violet,green,chocolate,purple # black,orange,red,red,blue,brown,purple,green,purple,green

linestyles: '-,--,--,--,--,--,--,--,--'

metrics: MMA,M.S.,Precision,Rep.,HA

