methods: mlifeat128megacoco,superpoint_fbm_megacoco,superpoint_fsm_megacoco,superpoint_selftrained_megacoco,superpoint

names: MLIFeat-MegaCOCO,SuperPoint-FBM,SuperPoint-FSM,SuperPoint-Selftrained,SuperPoint

colors: red,orange,lightcoral,blue,mediumblue #,dodgerblue,gold,violet,chocolate # black,orange,red,red,blue,brown,purple,green,purple,green

linestyles: '-,-,-,-,-'

metrics: MMA,M.S.,Precision,Rep.,HA

