#methods: mlifeat128megacoco,d2netss,d2netms,r2d2,aslfeat,superpoint,superpoint_selftrained_megacoco,affnet,dsp-sift

#names: MLIFeat,D2Net-SS,D2Net-MS,R2D2,ASLFeat,SuperPoint-Orig,SuperPoint-Impl,HesAffNet+HardNet++,DSP-SIFT
#colors: red,black,blue,dodgerblue,gold,violet,green,chocolate,purple # black,orange,red,red,blue,brown,purple,green,purple,green

#linestyles: '-,--,--,--,--,--,--,--,--'
methods: step1_9,step2_9,aslfeatv2_5k,step3_6,step3_7 #,mlifeat128megacoco step2_1, coco_9,step1_9,step1_9
names: step1,step2,aslfeatv2,step3_6,step3_7 #,mlifeat128megacoco Scalepoint_step2,
colors: blue,red,black,orange,green
linestyles: '--,--,--,--,--'


metrics: MMA,M.S.,Precision,Rep.,HA
feature_path: "/data/changwei/hpatch/"
