methods: mlifeat128megacoco,megpoint_bisenetv1,megpoint_deeplabv2

names: MegPoint,MegPoint_BiSeNetv1,MegPoint_DeepLabV2

colors: red,blue,gold # ,purple # ,dodgerblue,mediumblue ,violet,green,chocolate # black,orange,red,red,blue,brown,purple,green,purple,green

linestyles: '-,--,--' # ,--' # ,--,--,--,--,--,--'

metrics: MMA # ,M.S.,Precision,Rep.,HA



