hpatches:
    dataset_dir: '/data/yuyang/hpatches-sequences-release'
    resize: false
    grayscale: false

model:
    name: 'd2net_model'
    preprocessing: caffe
    max_edge: 1600
    max_sum_edges: 2800
    multiscale: true
    use_relu: true
    weights: '/home/yuyang/data/aachen/Aachen-Day-Night/weights/d2_tf.pth'

keys: keypoints,descriptors,shape
