hpatches:
    dataset_dir: '/data/yuyang/hpatches-sequences-release'
    resize: false
    grayscale: true

model:
    name: 'superpoint_model'
    detection_threshold: 0.015
    nms_dist: 4
    nms_radius: 4
    border_remove: 4
    weights: '/home/yuyang/data/aachen/Aachen-Day-Night/weights/superpoint_v1.pth'

keys: keypoints,descriptors,shape
