hpatches:
    dataset_dir: '/data/yuyang/hpatches-sequences-release'
    resize: false
    grayscale: false

model:
    name: 'r2d2_model'
    top_k: 5000
    scale_f: 1.189207115002721
    min_size: 256
    max_size: 1024
    min_scale: 0
    max_scale: 1.0
    reliability_thr: 0.7
    repeatability_thr: 0.7
    weights: '/home/yuyang/data/aachen/Aachen-Day-Night/weights/r2d2/r2d2_WAF_N16.pt'

keys: keypoints,descriptors,shape
