hpatches:
    dataset_dir: '/data/yuyang/hpatches-sequences-release'
    resize: false
    grayscale: false

model:
    name: 'aslfeat_model'
    model_path: '/home/changwei/scalepoint/evaluation_benchmark/aslfeatv2/model.ckpt-60000'
    max_dim: 2000
    config:
        kpt_n: 5000
        kpt_refinement: true
        deform_desc: 1
        score_thld: 0.5
        edge_thld: 10
        multi_scale: false
        multi_level: true
        nms_size: 3
        eof_mask: 5
        need_norm: true
        use_peakiness: true

keys: keypoints,descriptors,shape


