hpatches:
    dataset_dir: '/data/yuyang/hpatches-sequences-release'
    resize: false
    grayscale: false

model:
    name: 'affnet_model'
    weights: '/home/yuyang/data/aachen/Aachen-Day-Night/weights/affnet/AffNet.pth'
    descriptor_weights: '/home/yuyang/data/aachen/Aachen-Day-Night/weights/affnet/HardNet++.pth'

keys: keypoints,descriptors,shape

