hpatches:
    dataset_dir: '/data/yuyang/hpatches-sequences-release'
    resize: false
    grayscale: false

model:
    name: 'MLIFeat'
    detection_threshold: 0.9
    dim: 128
    nms_dist: 4
    nms_radius: 4
    border_remove: 4
    weights: '/home/yuyang/data/aachen/Aachen-Day-Night/weights/mlifeat128megacoco'
    l2: false

keys: keypoints,descriptors,shape



