dataset:
    name: 'aachen_visualization_dataset'
    dataset_root: '/home/yuyang/data/aachen/Aachen-Day-Night/images/images_upright'
    pair_list: '/home/yuyang/data/aachen/Aachen-Day-Night/image_pairs_to_match_night.txt'

model:
    name: 'MLIFeat'
    detection_threshold: 0.9
    dim: 128
    nms_dist: 4
    nms_radius: 4
    border_remove: 4
    weights: '/home/yuyang/data/aachen/Aachen-Day-Night/weights/mlifeat128megacoco'

keys: keypoints,descriptors,shape



