dataset:
    data_name: 'fmbench'
    data_split: ['TUM', 'KITTI', 'Tanks_and_Temples', 'CPC']
    # data_split: ['KITTI']
    data_root: '/home/yuyang/project/development/evaluation/FM-Bench'
    dump_root: '/home/yuyang/project/development/evaluation/FM-Bench/Features'
    dump_name: 'rootsiftcv'
    truncate: [0, null]
    overwrite: true
    stage: 'det'
    read_gray: false

model:
    name: 'rootsift_model'

keys: keypoints,descriptors



