dataset:
    data_name: 'fmbench'
    data_split: ['TUM', 'KITTI', 'Tanks_and_Temples', 'CPC']
    # data_split: ['KITTI']
    data_root: '/home/yuyang/project/development/evaluation/FM-Bench'
    dump_root: '/home/yuyang/project/development/evaluation/FM-Bench/Features'
    dump_name: 'mlifeat128megacoco08'
    truncate: [0, null]
    overwrite: true
    stage: 'det'
    read_gray: false

model:
    name: 'MLIFeat'
    detection_threshold: 0.8
    dim: 128
    nms_dist: 4
    nms_radius: 4
    border_remove: 4
    weights: '/home/yuyang/data/aachen/Aachen-Day-Night/weights/mlifeat128megacoco'

keys: keypoints,descriptors,scores



