dataset:
    data_name: 'fmbench'
    data_split: ['TUM', 'KITTI', 'Tanks_and_Temples', 'CPC']
    # data_split: ['KITTI']
    data_root: '/home/yuyang/project/development/evaluation/FM-Bench'
    dump_root: '/home/yuyang/project/development/evaluation/FM-Bench/Features'
    feature_root: '/home/yuyang/fmbench_results/dsp-sift/fmbench'
    dump_name: 'dspsift'
    truncate: [0, null]
    overwrite: true
    stage: 'det'
    read_gray: false

keys: keypoints,descriptors,scores



