name: depth_dispnets
trainer: depth_trainer.DepthTrainer

model:
    backbone: depth_net.DispNetS

test:
    dataset: make3d_dataset.Make3dDataset
    root: /home/yuyang/data/make3d/processed_dataset

train:
    adjust_lr: true
    lr: 0.001
    weight_decay: 0.0001
    lr_decay: 10
    poly_power: 0.9
    batch_size: 128
    epoch_num: 50
    log_freq: 50
    num_workers: 16
    validate_after: 0.0

    scales: [0.5, 0.75, 1.0]

    dataset: megadepth.MegaDepthNoOrd
    dataset_root: /data/localization/MegaDepthOrder/phoenix/S6/zl548/MegaDepth_v1
    list_root: /data/localization/MegaDepthOrder/list/train_list











