name: depth_dispnets_hourglass_distill
trainer: depth_trainer.DepthDistillTrainer

model:
    backbone: depth_net.DispNetS
    teacher: DIW_net.HourGlass
    # pretrained_ckpt: /home/yuyang/data/aachen/Aachen-Day-Night/weights/megadepth/dispnets_model.pt
    teacher_ckpt: /home/yuyang/data/aachen/Aachen-Day-Night/weights/megadepth/best_model_2_net_G.pth

test:
    dataset: make3d_dataset.Make3dDataset
    root: /home/yuyang/data/make3d/processed_dataset

train:
    adjust_lr: true
    lr: 0.001
    weight_decay: 0.0001
    lr_decay: 10
    poly_power: 0.9
    batch_size: 32
    epoch_num: 50
    log_freq: 50
    num_workers: 16
    validate_after: 0.0

    w_data: 1.0
    w_grad: 0.5

    do_scale: false
    scales: [0.5, 0.75, 1.0]

    small: 0.0
    seed: 8371
    dataset: megadepth.MegaDepthNoOrd
    dataset_root: /data/localization/MegaDepthOrder/preprocessed_no_ord











